CREATE TABLE users
(
    id INTEGER(11) PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);


CREATE TABLE lists
(
    id INTEGER(11) PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL
);


CREATE TABLE users_lists
(
    id INTEGER(11) PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    user_id INTEGER(11) NOT NULL,
    list_id INTEGER(11) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (list_id) REFERENCES lists (id) ON DELETE CASCADE
);


CREATE TABLE items
(
    id INTEGER(11) PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    lang1 VARCHAR(255) NOT NULL,
    lang2 VARCHAR(255) NOT NULL
);


CREATE TABLE lists_items
(
    id INTEGER(11) PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    list_id INTEGER(11) NOT NULL,
    item_id INTEGER(11) NOT NULL,
    FOREIGN KEY (list_id) REFERENCES lists (id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);